apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replicaset
  labels:
    name: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      name: nginxreplicaset
  template:
    metadata:
      labels:
        name: nginxreplicaset
    spec:
     containers:
     - name: nginx
       image: niginx:latest
       ports:
       - containerPort: 80
        